// Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// User
export const FETCH_USER = 'FETCH_USER';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

// Input
export const CHANGE_INPUT = 'CHANGE_INPUT';
export const TOUCH_INPUT = 'TOUCH_INPUT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const CLEAR_FORM = 'CLEAR_FORM';
export const FETCH_FORM_DATA = 'FETCH_FORM_DATA';

// Campgrounds
export const FETCH_ALL_CAMPGROUNDS = 'FETCH_ALL_CAMPGROUNDS';

export const FETCH_ONE_CAMPGROUND_START = 'FETCH_ONE_CAMPGROUND_START';
export const FETCH_ONE_CAMPGROUND_SUCCESS = 'FETCH_ONE_CAMPGROUND_SUCCESS';
export const FETCH_ONE_CAMPGROUND_FAIL = 'FETCH_ONE_CAMPGROUND_FAIL';

export const FETCH_ONE_CAMPGROUND_COORDS = 'FETCH_ONE_CAMPGROUND_COORDS';

export const FETCH_ALL_CAMPGROUNDS_BY_USER = 'FETCH_ALL_CAMPGROUNDS_BY_USER';

export const FETCH_CAMPGROUNDS_START = 'FETCH_CAMPGROUNDS_START';
export const FETCH_CAMPGROUNDS_SUCCESS = 'FETCH_CAMPGROUNDS_SUCCESS';
export const FETCH_CAMPGROUNDS_FAIL = 'FETCH_CAMPGROUNDS_FAIL';

export const DELETE_CAMPGROUND_START = 'DELETE_CAMPGROUND_START';
export const DELETE_CAMPGROUND_SUCCESS = 'DELETE_CAMPGROUND_SUCCESS';
export const DELETE_CAMPGROUND_FAIL = 'DELETE_CAMPGROUND_FAIL';

export const SUBMIT_EDITED_CAMPGROUND_START = 'SUBMIT_EDITED_CAMPGROUND_START';
export const SUBMIT_EDITED_CAMPGROUND_SUCCESS =
  'SUBMIT_EDITED_CAMPGROUND_SUCCESS';
export const SUBMIT_EDITED_CAMPGROUND_FAIL = 'SUBMIT_EDITED_CAMPGROUND_FAIL';

export const CREATE_NEW_CAMPGROUND_START = 'CREATE_NEW_CAMPGROUND_START';
export const CREATE_NEW_CAMPGROUND_SUCCESS = 'CREATE_NEW_CAMPGROUND_SUCCESS';
export const CREATE_NEW_CAMPGROUND_FAIL = 'CREATE_NEW_CAMPGROUND_FAIL';

// Reviews
export const SUBMIT_REVIEW_START = 'SUBMIT_REVIEW_START';
export const SUBMIT_REVIEW_SUCCESS = 'SUBMIT_REVIEW_SUCCESS';
export const SUBMIT_REVIEW_FAIL = 'SUBMIT_REVIEW_FAIL';

export const SUBMIT_EDITED_REVIEW_START = 'SUBMIT_EDITED_REVIEW_START';
export const SUBMIT_EDITED_REVIEW_SUCCESS = 'SUBMIT_EDITED_REVIEW_SUCCESS';
export const SUBMIT_EDITED_REVIEW_FAIL = 'SUBMIT_EDITED_REVIEW_FAIL';

export const FETCH_ONE_REVIEW_START = 'FETCH_ONE_REVIEW_START';
export const FETCH_ONE_REVIEW_SUCCESS = 'FETCH_ONE_FETCH_ONE_REVIEW_SUCCESS';
export const FETCH_ONE_REVIEW_FAIL = 'FETCH_ONE_FETCH_ONE_REVIEW_FAIL';

export const DELETE_REVIEW_START = 'DELETE_REVIEW_START';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';

// Star rating
export const ADD_STAR_RATING = 'ADD_STAR_RATING';

// Image upload
export const IMAGE_UPLOAD_START = 'IMAGE_UPLOAD_START';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAIL = 'IMAGE_UPLOAD_FAIL';
